services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    env_file: .env

  redis:
    image: redis:6-alpine
    restart: always

  app:
    image: nextcloud:21-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=$SITE_DOMAIN
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - REDIS_HOST=redis
    env_file: .env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:21-fpm-alpine
    restart: always
    volumes_from:
      - app
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  web:
    image: caddy:2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    volumes_from:
      - app:ro
    depends_on:
      - app

volumes:
  db:
  nextcloud:
  caddy_data:
    external: true
  caddy_config:
